### ISSUE TITLE
引述现行标准

### ISSUE THREAD

**Issue by liyishuai** [sparanoid/chinese-copywriting-guidelines#100]
尊敬的开发者、维护人员：
你们好！

在下国语不精，谨以普通话、简体字陈述。

了解本项目之前，我排版主要依据如下标准：
- 中华人民共和国国家标准GB/T 15834—2011号《标点符号用法》
- 中华人民共和国新闻出版行业标准CY/T 154—2017号《中文出版物夹用英文的编辑规范》

其中部分规则与此处略有出入，例如：
- > 中英文之间需要增加空格
   
   异于《中文出版物夹用英文的编辑规范》第8.1节：
   > 中文文本中夹用英文时，应根据所选用的中英文字体、字符间距以及排版的视觉效果决定英文词句与中文文字之间是否留有空格间距。如留空格，应保证体例的统一。
- > 不重复使用标点符号

   #32 已讨论。

- > 简体中文使用直角引号

   #83 称其不合规，但根据《标点符号用法》第5.2节“竖排文稿标点符号的位置和书写形式”：
   > 5.2.3 引号改用双引号“﹃”“﹄”和单引号“﹁”“﹂”，……

   直角引号在竖排文稿中是正确用法，但一般的文本不包含排版信息，故其合规与否取决于打开方式。

为减少读者疑虑，我谨提议：在指北中引述各地现行标准，并指出对其取舍的考量。

感谢你们对该项目的辛勤付出！

**Comment by Copay** [comment]
https://www.w3.org/TR/clreq/
