### ISSUE TITLE
是否可以明确一下日期的书写格式

### ISSUE THREAD

**Issue by undeadway** [sparanoid/chinese-copywriting-guidelines#102]
各位维护者你们好，按照现行的标准，因为日期混合了中文+数字，所以日期格式似乎应该写成如下的格式：
```
这条 ISSUSE 在 2019 年 12 月 25 日 发布
```
个人感觉日期部分有些太空，是否可以考虑将日期中间的空格删除，修改为：
```
这条 ISSUSE 在 2019年12月25日 发布
```

将日期和普通的英文、数字空格的用法区分开。

**Comment by HumJ0218** [comment]
大概看了一遍《GB/T 7408-2005 数据元和交换格式 信息交换 日期和时间表示法》，里面暂时没发现关于日期与其他文字混排时的排版要求。但根据规范文本自身的排版风格来看，日期时间的数字与汉字按照正常间隔处理，不需要另加任何空格。例如：

第 2 页
>  现在普遍采用的历法系统，出现于 1582 年，它所定义的年比朱利安日历更为接近回归年。

第 6 页
>  星期日历的参考点是把 2000 年 1 月 1 日定为星期六。
> ……
> 1995 年 1 月 1 日星期日是 1994 年的第 52 个星期的第 7 天。

第 13 页
> 以下为 UTC 时间 23 时 20 分 30 秒的完全表示与降低精度表示法的实例。

第 14 页
>  实例中使用了日内瓦当地时间（通常早于协调世界时 1 小时）以及纽约当地时间（迟于协调世界时 5 小时）15 时 27 分 26 秒的时间完全表示法，以及当地时间与协调世界时的时差的表示。

仅供参考

**Comment by sgalal** [comment]
> 但根据规范文本自身的排版风格来看，日期时间的数字与汉字按照正常间隔处理，不需要另加任何空格

但你给的例子是加了空格的

**Comment by HumJ0218** [comment]
> 但你给的例子是加了空格的

数字正常加，日期整体不用再加

**Comment by liyishuai** [comment]
Duplicate of #108

**Comment by undeadway** [comment]
> 大概看了一遍《GB/T 7408-2005 数据元和交换格式 信息交换 日期和时间表示法》，里面暂时没发现关于日期与其他文字混排时的排版要求。但根据规范文本自身的排版风格来看，日期时间的数字与汉字按照正常间隔处理，不需要另加任何空格。例如：
> 
> 第 2 页
> 
> > 现在普遍采用的历法系统，出现于 1582 年，它所定义的年比朱利安日历更为接近回归年。
> 
> 第 6 页
> 
> > 星期日历的参考点是把 2000 年 1 月 1 日定为星期六。
> > ……
> > 1995 年 1 月 1 日星期日是 1994 年的第 52 个星期的第 7 天。
> 
> 第 13 页
> 
> > 以下为 UTC 时间 23 时 20 分 30 秒的完全表示与降低精度表示法的实例。
> 
> 第 14 页
> 
> > 实例中使用了日内瓦当地时间（通常早于协调世界时 1 小时）以及纽约当地时间（迟于协调世界时 5 小时）15 时 27 分 26 秒的时间完全表示法，以及当地时间与协调世界时的时差的表示。
> 
> 仅供参考

既然有国标，那就不用多说什么了
