### ISSUE TITLE
發現一處筆誤

### ISSUE THREAD

**Issue by cybersword** [sparanoid/chinese-copywriting-guidelines#104]
> 不要使用不道地的縮寫

筆誤：道地
應爲：地道

**Comment by yoonhakcher** [comment]
> 實在的、真正的。
> 元·無名氏《百花亭·第三折》：「這果是家園製造，道地收來也。」《初刻拍案驚奇·卷二六》：「老和尚在裡頭看見徒弟引得個小夥子進來，道：『是個道地貨來了。』」
> 也作「地道」。

https://www.moedict.tw/%E9%81%93%E5%9C%B0
