### ISSUE TITLE
英文书籍、报刊、文章名不应使用书名号

### ISSUE THREAD

**Issue by duyuang** [sparanoid/chinese-copywriting-guidelines#120]
在本指南里的“[遇到完整的英文整句、特殊名詞，其內容使用半形標點](https://github.com/sparanoid/chinese-copywriting-guidelines#%E9%81%87%E5%88%B0%E5%AE%8C%E6%95%B4%E7%9A%84%E8%8B%B1%E6%96%87%E6%95%B4%E5%8F%A5%E7%89%B9%E6%AE%8A%E5%90%8D%E8%A9%9E%E5%85%B6%E5%85%A7%E5%AE%B9%E4%BD%BF%E7%94%A8%E5%8D%8A%E5%BD%A2%E6%A8%99%E9%BB%9E)”章节，使用了这种不符合标准的例子：

> 推薦你閱讀《Hackers & Painters: Big Ideas from the Computer Age》，非常的有趣。

而根据 [CY/T 154-2017](http://sxqx.alljournal.cn/uploadfile/sxqx/20190304/CY%20T154%E2%80%942017%20%E4%B8%AD%E6%96%87%E5%87%BA%E7%89%88%E7%89%A9%E5%A4%B9%E7%94%A8%E8%8B%B1%E6%96%87%E7%9A%84%E7%BC%96%E8%BE%91%E6%A0%87%E5%87%86.pdf) 标准第10条——中文句子中夹有英文书籍名、报刊名时，不应借用中文书名，而应以英文斜体表示；中文句子内夹有英文文章的标题，标题应使用英文正体字，以中文引号标示。

![image](https://user-images.githubusercontent.com/35097840/87645878-af5bed00-c780-11ea-99d2-1adc88750b0f.png)

**Comment by liyishuai** [comment]
#115 should fix this.
