### ISSUE TITLE
为美化排版使用的全角英文数字与汉字之间是否需要增加空格？

### ISSUE THREAD

**Issue by HumJ0218** [sparanoid/chinese-copywriting-guidelines#121]
> 这个蛋糕只卖 １０００ 元
> 那个乱七八糟的东西就不需要这么多钱

> 这个蛋糕只卖１０００元
> 那个乱七八糟的东西就不需要这么多钱

个人觉得不需要增加空格（现在示例里面是加了空格的）

**Comment by KagurazakaHanabi** [comment]
可参考「全角标点与其他字符之间不加空格」

**Comment by sgalal** [comment]
我认为不用加空格
