### ISSUE TITLE
中英文混排，英文位于句首和句尾，只需在句首的英文后和句尾的英文前加空格吗

### ISSUE THREAD

**Issue by sunchaser-lilu** [sparanoid/chinese-copywriting-guidelines#181]
例如：Java 中线程池的核心实现类为 ThreadPoolExecutor。

请问以上是否合理？

**Comment by liyishuai** [comment]
https://github.com/sparanoid/chinese-copywriting-guidelines/blob/73580f1aeb706aa79851daeec258ba5115244d3a/README.zh-Hans.md?plain=1#L73-L83

**Comment by sunchaser-lilu** [comment]
> https://github.com/sparanoid/chinese-copywriting-guidelines/blob/73580f1aeb706aa79851daeec258ba5115244d3a/README.zh-Hans.md?plain=1#L73-L83

感谢回复
