### ISSUE TITLE
HTML5 needs no space

### ISSUE THREAD

**Issue by andyshuxin** [sparanoid/chinese-copywriting-guidelines#19]
In the section concerning abbreviations, this sentence is used as a example:
<blockquote>我們需要一位熟悉 JavaScript、HTML 5，至少理解一种框架（如 Backbone.js、AngularJS、React 等）的前端開發者。</blockquote>

[A WHATWG blog](https://blog.whatwg.org/spelling-html5) states that “HTML5” should not contain spaces :
<blockquote>What’s the right way to spell “HTML5”? The short answer is: “HTML5” (without a space).</blockquote>

One can also see this on the [W3C HTML5 homepage](http://www.w3.org/TR/html5/).

**Comment by sparanoid** [comment]
Good catch @andyshuxin
