### ISSUE TITLE
语病：“即使……但是”搭配不当

### ISSUE THREAD

**Issue by Dropless-arch** [sparanoid/chinese-copywriting-guidelines#190]
“即使中国大陆的标点符号用法允许重复使用标点符号，但是这么做会破坏句子的美观性。”

“即使” 和 “但是” 不能连用。

正确应为：
即使中国大陆的标点符号用法允许重复使用标点符号，这么做会破坏句子的美观性。
或
中国大陆的标点符号用法允许重复使用标点符号，但是这么做会破坏句子的美观性。
或
虽然中国大陆的标点符号用法允许重复使用标点符号，但是这么做会破坏句子的美观性。

**Comment by liyishuai** [comment]
欢迎来到GitHub社区！感谢您对本专案的关注。
我注意到这是您第一次提交问题文档（Issue），故提出若干关于使用GitHub之建议：
1. 在撰写文本时，可采用[Markdown](https://docs.github.com/zh/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax)语法，更加美观；
2. 有明确的改动建议时，可直接[创建拉取请求](https://docs.github.com/zh/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request)，样式可参考 #191
3. 标题中，“语病”为客观陈述，而“非常低级”为主观评价，前者比后者更有利于讨论工作的展开，故建议修改标题为：`语病：“即使……但是”搭配不当`。
