### ISSUE TITLE
在wordpress中与markdown插件的冲突

### ISSUE THREAD

**Issue by hausen1012** [sparanoid/chinese-copywriting-guidelines#192]
我在wordpress 中使用了 https://github.com/terrylinooo/githuber-md/ 这个插件，再使用 如下代码过滤

```sh
function pk_chinese_format($content)
{
    include_once dirname(__FILE__) . '/../lib/ChineseTypesetting.php';
    $typesetting = new ChineseTypesetting();
    $content = $typesetting->insertSpace($content);
    $content = $typesetting->removeSpace($content);
    return $typesetting->full2Half($content);
}

if (pk_is_checked('chinese_format')) {
    add_filter('the_content', 'pk_chinese_format', 199);
}
```
会导致markdown代码块有些被压缩成一行
![image](https://github.com/sparanoid/chinese-copywriting-guidelines/assets/50026605/0511cb84-3f20-41a1-b324-11603d4a78a3)
正常应该是这样。
![image](https://github.com/sparanoid/chinese-copywriting-guidelines/assets/50026605/22502fef-16c9-451d-aa18-038f6f8ff305)

**Comment by sparanoid** [comment]
这个 issue 好像跟本项目没有直接关系？如果你使用的是 https://github.com/jxlwqq/chinese-typesetting 这个项目，可能是该项目与 githuber-md 的兼容性导致的，请前往对应的仓库去提 issue 或按照项目本身提供的反馈渠道进行反馈
