### ISSUE TITLE
关于数字和单位之间是否应该加空格

### ISSUE THREAD

**Issue by UnityAlvin** [sparanoid/chinese-copywriting-guidelines#199]
像原文中举出的例子，比如「1000元」这种，那正确写法为「1000 元」，这我可以理解，但如果单位是英文这种，是否应该继续添加空格呢？举几个简单的例子，比如「64GB」、「1MB」、「500GB」、「1TB」、「720P」、「1080P」，据我观察，这些在苹果官网是没有加空格的。

而像「25fps」、「30fps」、「60fps」这些在数字跟单位之间又是加了空格的，包括这些单位后面还有中文的那种情况，跟中文之间也是有空格的，这样看它又遵从了这个规范。

那这种，「1s」、「1ms」、「1h」还有很多我暂时想不出来的例子，这些需不需要遵从这个规范呢？

**Comment by QilanLin** [comment]
根据 ChatGPT (GPT-4):

在技术和科学写作中，通常建议在数字和单位之间加入一个空格，以便更好地阅读，并符合国际标准。例如，"64 GB" 会是更正式正确的写法。这符合国际单位制（SI）以及各种风格指南，如 IEEE 和 APA。

然而，在营销材料、产品名称或非正式写作中经常会省略空格，例如 "64 GB"。这通常是出于视觉紧凑性或品牌推广的原因。

因此，选择 "64GB" 和 "64 GB" 可以取决于上下文：

- 对于学术论文、技术文档或正式写作，使用 "64 GB" 会更安全。
- 对于产品名称、营销材料或非正式写作，"64GB" 是常用的。

这些都是一般指导原则，最重要的是在文档或项目中保持一致。

**Comment by liyishuai** [comment]
Duplicate of #163

**Comment by UnityAlvin** [comment]
根据 ChatGPT (GPT-4):

在技术和科学写作中，通常建议在数字和单位之间加入一个空格，以便更好地阅读，并符合国际标准。例如，"64 GB" 会是更正式正确的写法。这符合国际单位制（SI）以及各种风格指南，如 IEEE 和 APA。

然而，在营销材料、产品名称或非正式写作中经常会省略空格，例如 "64 GB"。这通常是出于视觉紧凑性或品牌推广的原因。

因此，选择 "64GB" 和 "64 GB" 可以取决于上下文：

对于学术论文、技术文档或正式写作，使用 "64 GB" 会更安全。
对于产品名称、营销材料或非正式写作，"64GB" 是常用的。

Thanks for you explanation :) @QilanLin

**Comment by UnityAlvin** [comment]
根据 ChatGPT (GPT-4):

在技术和科学写作中，通常建议在数字和单位之间加入一个空格，以便更好地阅读，并符合国际标准。例如，"64 GB" 会是更正式正确的写法。这符合国际单位制（SI）以及各种风格指南，如 IEEE 和 APA。

然而，在营销材料、产品名称或非正式写作中经常会省略空格，例如 "64 GB"。这通常是出于视觉紧凑性或品牌推广的原因。

因此，选择 "64GB" 和 "64 GB" 可以取决于上下文：

对于学术论文、技术文档或正式写作，使用 "64 GB" 会更安全。
对于产品名称、营销材料或非正式写作，"64GB" 是常用的。

Thanks for you explanation :) @QilanLin

**Comment by QilanLin** [comment]
哈哈 GPT讨论的”数字和单位之间是否加空格“是纯英文写作中的操作，而不是你问的中文的 感觉我问ChatGPT没问对 就删了

**Comment by UnityAlvin** [comment]
> 哈哈 GPT讨论的”数字和单位之间是否加空格“是纯英文写作中的操作，而不是你问的中文的 感觉我问ChatGPT没问对 就删了

怪不得我从邮箱跳转到这个 issue 界面找不到你的回复，你删了那就解释通了。那这样的话，GPT 针对中文写作有答案吗？如果没有的话，那套用英文的这套我感觉没什么问题，无非就是用中文替换英文罢了。
