### ISSUE TITLE
关于重复使用标点符号的用法

### ISSUE THREAD

**Issue by ddanist** [sparanoid/chinese-copywriting-guidelines#32]
据教育部的[《标点符号用法》](http://www.moe.gov.cn/ewebeditor/uploadfile/2015/01/13/20150113091548267.pdf)4.3.3.3 条：表示声音巨大或声音不断加大时，可叠用叹号；表达强烈语气时，也可叠用叹号，最多叠用三个叹号。在没有异常强烈的情感表达需要时不宜叠用叹号。

因此，错误事例中「德國隊竟然戰勝了巴西隊！！」是符合语法的正确用法。

但重复使用标点确实不太「好看」。

**Comment by sparanoid** [comment]
> 但重复使用标点确实不太「好看」。

對，確實不好看。

參考《用法》的例子：

<img width="378" alt="screen shot 2016-02-17 at 11 16 45 pm" src="https://cloud.githubusercontent.com/assets/96356/13114022/adc48682-d5cc-11e5-9180-6080f0709428.png">

其中標點的使用本身就比較詭異，看樣子用的是半形標點，並且在每組感歎號的最後還加上了一個半形空格。而我不推薦在中文文案中這樣使用半形標點，套用到這邊的用法會變成這樣：

<img width="286" alt="screen shot 2016-02-17 at 11 20 47 pm" src="https://cloud.githubusercontent.com/assets/96356/13114134/1faacf0e-d5cd-11e5-8702-7b33f27a2f99.png">

所以請盡量避免重複使用標點。

**Comment by HeavySnowJakarta** [comment]
> > 但重复使用标点确实不太「好看」。
> 
> 對，確實不好看。
> 
> 參考《用法》的例子：
> 
> <img width="378" alt="screen shot 2016-02-17 at 11 16 45 pm" src="https://cloud.githubusercontent.com/assets/96356/13114022/adc48682-d5cc-11e5-9180-6080f0709428.png">
> 
> 其中標點的使用本身就比較詭異，看樣子用的是半形標點，並且在每組感歎號的最後還加上了一個半形空格（請注意冒號和逗號後面卻沒有）。而我不推薦在中文文案中這樣使用半形標點，套用到這邊的用法會變成這樣：
> 
> <img width="286" alt="screen shot 2016-02-17 at 11 20 47 pm" src="https://cloud.githubusercontent.com/assets/96356/13114134/1faacf0e-d5cd-11e5-8702-7b33f27a2f99.png">
> 
> 所以請盡量避免重複使用標點。
> 

不无道理。但是我希望能在“不重复使用标点”处引述这一内容，以减少争议。
