### ISSUE TITLE
在简体中文中，在一些情况下允许叠用叹号不超过三次。

### ISSUE THREAD

**Issue by jiacj** [sparanoid/chinese-copywriting-guidelines#45]
在 2011 年 12 月 31 日发布的《标点符号用法》中有以下规定：“4.3.3.3 表示声音巨大或声音不断加大时，可叠用叹号；表达强烈语气时，也可叠用叹号，最多叠用三个叹号。在没有异常强烈的情感表达需要时不宜叠用叹号。”

**Comment by sparanoid** [comment]
是这样的，《用法》中的规则是「不宜」，而我对文案的建议是尽量避免

这里没有对错之分，这里只是从视觉上和文案的语境上考虑，所以我觉得并不冲突
