### ISSUE TITLE
如何处理表情文本

### ISSUE THREAD

**Issue by CatTail** [sparanoid/chinese-copywriting-guidelines#47]
> 例如我很 😄。

如何处理表情符号和文本，标点之间的留白？

**Comment by sparanoid** [comment]
我认为绘文字通常情况下应该视为「普通的英文字符」，继承英文字符的规则，唯一的区别是绘文字之间不需要增加空格，例如：

> 今天出去 🛒，竟然踩到了 💩，非常的 😫

> 晚上要与好友吃 🍣🍤🍙🍘，然后去玩 🎡🎢！

而不是：

> 今天出去🛒，竟然踩到了💩 ，非常的😫

> 晚上要與好友吃 🍣 🍤 🍙 🍘，然後去玩 🎡 🎢！

不过我认为绘文字并不会大量出现在正式的文案排版中
