### ISSUE TITLE
可以在文中推荐一个 Chrome 插件（空格之神）

### ISSUE THREAD

**Issue by YouthLin** [sparanoid/chinese-copywriting-guidelines#49]
[空格之神](https://chrome.google.com/webstore/detail/paphcfdffjnbcgkokihcdjliihicmbpd)  ( https://chrome.google.com/webstore/detail/paphcfdffjnbcgkokihcdjliihicmbpd )
自动排版网页，在中英文之间加上空格，效果基本符合本指北。

只是以前发现的一个插件，并不是给它打广告。

**Comment by sparanoid** [comment]
我在由于要不要添加，因为这个 repo 的主要目的是用于帮助创作者撰写更规范的文案，这个插件则是让读者去自主修正不规范的文案。
