### ISSUE TITLE
目录的问题

### ISSUE THREAD

**Issue by October22** [sparanoid/chinese-copywriting-guidelines#82]
文档中未生成目录。请问是使用了不兼容 GFM 的语法，还是有意留下的彩蛋呢？
```markdown
{:.no_toc}

    * TOC {:toc}
```
如果是意外，可以试试这个工具 [DocToc](https://github.com/thlorenz/doctoc)，自动生成 TOC，便于项目管理 :smile: 也避免了手动书写带中文锚点。

**Comment by sparanoid** [comment]
这个是 [Kramdown 的语法](https://kramdown.gettalong.org/converter/html.html#toc)。目前是用在 [Jekyll 上](https://sparanoid.com/note/chinese-copywriting-guidelines/)

我是曾经抱有一丝希望 GitHub 这边可以支持这种语法的，但似乎短期是 [不可能的](https://github.com/isaacs/github/issues/215)

**Comment by October22** [comment]
谢谢您的回复！

Github Pages 服务是 Jekyll 引擎，如果显示的页面是托管在这个页面上，就可以提供 TOC 的扩展吧。

[GFM](https://help.github.com/articles/github-flavored-markdown/) 是基于 CommonMark 扩展。CommonMark 确了 Markdown 中不明确的语法，还是偏重于简单的文档。因此对于有复杂要求的文档我偏爱 [AsciiDoc](https://asciidoctor.org/ "Ruby 的实现")，不过我并不是为了推荐某个项目，我也推荐了 DocToc 这个临时目录生成工具。

我提这个 Issue 的目的出于对这个项目的喜爱，希望它能更好看。我也打算用 adoc 实现一次。 :smile: 再次谢谢您的答疑。
