### ISSUE TITLE
建议为引号用法加上适用场景的特殊说明

### ISSUE THREAD

**Issue by zxteloiv** [sparanoid/chinese-copywriting-guidelines#83]
使用方块引号的方式，在大陆地区是明确地违反国标[1]的行为，正规出版物上必然要禁止。
有鉴于此，这条倡议就完全变成了个人喜好，而让本文的指导建议上的意义大打折扣。

[1] http://www.moe.gov.cn/ewebeditor/uploadfile/2015/01/13/20150113091548267.pdf

**Comment by MasterPa** [comment]
多谢提醒！你说的这一点我们是知道的。不过本文风指南是为我司内部使用所设计，主要目标是用于品牌形象建设；而非用于正规出版物。

**Comment by sparanoid** [comment]
这个在很多平台上已经有不少讨论了，因此，本「指北」已将「简体中文使用直角引号」列在争议条目下，并已附上了相应说明：

> 以下用法略帶有個人色彩，即：無論是否遵循下述規則，從語法的角度來講都是正確的。

至于：

> 而让本文的指导建议上的意义大打折扣。

本「指北」的侧重点为**文案排版**，大部分为网页、广告文案、软件界面所制订。而非国标那样的指导思想或基本原则。您可以将其理解为类似 Google Style Guides、Airbnb JavaScript Style Guide 一样的存在。

**Comment by sorz** [comment]
[1] 所指标准 GB/T 15834 是「推荐性国家标准」，是自愿采用而非强制实行的。
