### ISSUE TITLE
有谁知道这类单位需要怎么处理吗？

### ISSUE THREAD

**Issue by Xeath** [sparanoid/chinese-copywriting-guidelines#87]
类似于 `10 元/小时`这种该如何添加空格呢？还是应该使用类似 `10 Yuan/Hour` 英语格式或者 `10 元每小时`的中文格式？
在整句话中，比如「今天租用了一台 10 元/小时的比亚迪小车」，该如何正确使用空格？

**Comment by sparanoid** [comment]
这类只要做到在项目中格式统一即可

至于空格用法的话，你举的那个例子是正确的

**Comment by uninyhart** [comment]
LaTeX 中有一个宏包 `siunitx` ，它提供的命令 `\SI` 给出的空格是 1/4 个空格 (`\,`)。

我不是很清楚怎么在网页中*方便地*打 1/4 个空格。这里还有一些兼容问题。

我的解决方法：使用 MathJax 的插件 siunitx。

不知道有没有什么其他好的建议？或者直接干脆打空格？

**Comment by BinkZhu** [comment]
在 Apple 官网中是这样的：
- From $19.99/mo.per month or $479
- 折抵换购 iPhone XR 仅 RMB 200/月起
- RMB 258/月或 RMB 6199 起

仅供参考。

**Comment by HumJ0218** [comment]
RMB 258/_月或_ RMB 6199 起

月和或之间应该加空格的吧，感觉这个本身就排错了

10 是数字， 元/小时 是一整个单位。分开成 10 元 / 小时 就有一种 10×元÷小时 的感觉，实际应该是 10×(元÷小时) 才对吧

好像又扯出来一个嵌入简单算式时候如何添加空格的问题来了
