### ISSUE TITLE
简体版本示例中关于句号之后是否需要空格的疑问

### ISSUE THREAD

**Issue by Toonter** [sparanoid/chinese-copywriting-guidelines#91]
在 `简体中文` -> `空格` -> `中英文之间需要增加空格` -> `完整的正确用法` 示例中，每个句号后面都有一个空格。

不知道后续的 `全角标点与其他字符之间不加空格` 表示的全角符号是否包括 **全角标点** 与 **汉字**。

以及 `简体中文` -> `标点符号` -> `使用全角中文标点` 的示例中，叹号和问号结束一句话的时候，后面都是没有接空格的。

**Comment by WenryXu** [comment]
我认为这是示例中的失误。

**Comment by sparanoid** [comment]
Fixed
