### ISSUE TITLE
Possible typo: 介面

### ISSUE THREAD

**Issue by imba-tjd** [sparanoid/chinese-copywriting-guidelines#99]

**Comment by Odeandie** [comment]
[https://github.com/sparanoid/chinese-copywriting-guidelines/blob/master/README.zh-CN.md#%E7%94%A8-text-spacing-%E6%9D%A5%E6%8C%BD%E6%95%91](url)例如 macOS、iOS、Windows 等用户介面

**Comment by liyishuai** [comment]
https://github.com/sparanoid/chinese-copywriting-guidelines/blob/503d1d4fb1351134d4210665b4797d1b9d200f62/README.zh-CN.md#L96

**Comment by imba-tjd** [comment]
I mean it's 界面 rather than 介面

**Comment by liyishuai** [comment]
@imba-tjd I'm locating the typo you mentioned so that maintainers can review it more easily (I believe @Odeandie inteded the same).

**Comment by novolife** [comment]
介面好像是台湾地区用法？我搜了一下感觉大多数是台湾在用

**Comment by imba-tjd** [comment]
我不知道啊，所以我开的是issue而不是PR。反正简体是需要改的，如果确定繁体是对的那就只改简体咯。
